// ============================================================
//  TRANSLATION FILE - ENGLISH (en.js)
//  EdTech Day Yaoundé 2026
//  All English translations of the website texts are stored here.
// ============================================================

const TRANSLATIONS_EN = {

    // ── META ──────────────────────────────────────────────────
    "page.title": "EdTech Day Yaoundé 2026 - Digitalizing Education in the Era of Generative AI",
    "page.description": "EdTech Day Yaoundé 2026, Cameroon's flagship educational technology event, jointly held with the CAITED Conference, May 27-28, 2026, University of Yaoundé.",

    // ── NAVIGATION ────────────────────────────────────────────
    "nav.home": "Home",
    "nav.about": "About",
    "nav.programme": "Programme",
    "nav.exposition": "Exhibition",
    "nav.hackathon": "Hackathon",
    "nav.speakers": "Speakers",
    "nav.workshops": "Workshops",
    "nav.partners": "Partners",
    "nav.register": "Registration",
    "nav.register.btn": "Register",
    "nav.lang.btn": "FR/EN",

    // ── LANGUAGE SWITCHER ─────────────────────────────────────
    "lang.switcher.title": "Choisir la langue / Choose language",
    "lang.fr": "Français",
    "lang.en": "English",

    // ── TRANSLATION NOTICE ────────────────────────────────────
    "notice.title": "Automatic Translation",
    "notice.text": "This page is automatically translated. Some terms may not be entirely accurate.",

    // ── HERO ──────────────────────────────────────────────────
    "hero.title": "EdTech Day Yaoundé 2026",
    "hero.subtitle": "Digitalizing Education in the Era of Generative AI: What Efficiency Levers for Cameroon?",
    "hero.description": "Cameroon's flagship educational technology event, organized jointly with the CAITED Conference. May 28, 2026 is dedicated to the EdTech Summit in Yaoundé.",
    "hero.btn.register": "Register Now",
    "hero.btn.programme": "View Programme",

    // ── COUNTDOWN ────────────────────────────────────────────
    "countdown.title": "Countdown",
    "countdown.days": "Days",
    "countdown.hours": "Hours",
    "countdown.minutes": "Minutes",
    "countdown.seconds": "Seconds",
    "countdown.caited": "May 27: CAITED 2026 Conference",
    "countdown.caited.link": "Visit website",
    "countdown.summit": "May 28: EdTech Summit Yaoundé",
    "countdown.started": "The event has started!",

    // ── STATS ─────────────────────────────────────────────────
    "stats.days": "Event Days",
    "stats.companies": "EdTech Companies",
    "stats.participants": "Expected Participants",
    "stats.speakers": "Expert Speakers",

    // ── ABOUT ─────────────────────────────────────────────────
    "about.title": "About the Event",
    "about.lead": "EdTech Day Yaoundé 2026 is the reference event dedicated to educational technologies in Cameroon and Central Africa.",
    "about.p1": "Organized jointly with the <strong>CAITED 2026 Conference (Conference on Advances in Computer Science and Educational Technologies for Development)</strong>, this three-day event brings together key players in the educational, technological, and entrepreneurial sectors.",
    "about.p2": "<strong>May 28, 2026</strong> is specially dedicated to the <strong>EdTech Summit in Yaoundé</strong>, a strategic event that brings together policy makers, investors, entrepreneurs and educators to shape the future of digital education in Cameroon.",
    "about.theme.label": "2026 Theme",
    "about.theme.text": "\"Digitalizing Education in the Era of Generative AI: What Efficiency Levers for Cameroon?\"",
    "about.theme.desc": "Exploring how generative artificial intelligence can transform teaching and learning in the Cameroonian context.",
    "about.card.title": "Alongside the CAITED 2026 Conference",
    "about.card.text": "The 2nd edition of EdTech Day Yaoundé held jointly with the CAITED 2026 international conference creates a unique synergy between academic research and entrepreneurial innovation oriented toward sustainable development.",
    "about.day1.label": "CAITED 2026 Conference",
    "about.day2.label": "EdTech Summit",

    // ── OBJECTIVES ───────────────────────────────────────────
    "objectives.title": "EdTech Day 2026 Objectives",
    "obj.innovation.title": "Innovation",
    "obj.innovation.text": "Showcasing generative AI innovations applied to education and their potential for Cameroon.",
    "obj.networking.title": "Networking",
    "obj.networking.text": "Creating connections between EdTech startups, investors, educators and policy makers.",
    "obj.business.title": "Business",
    "obj.business.text": "Facilitating business opportunities and partnerships in the Cameroonian EdTech ecosystem.",
    "obj.training.title": "Training",
    "obj.training.text": "Training teachers and educators in digital tools and generative AI for education.",

    // ── PROGRAMME ────────────────────────────────────────────
    "programme.title": "3-Day Programme",
    "programme.lead": "An event rich in conferences, workshops, demonstrations and networking",
    "programme.day1.tab": "Day 1",
    "programme.day1.sub": "June 8 - CAITED Conference",
    "programme.day2.tab": "Day 2",
    "programme.day2.sub": "June 9 - CAITED Conference",
    "programme.day3.tab": "Day 3",
    "programme.day3.sub": "June 10 - EdTech Summit",

    // Day 1
    "prog.d1.e1.title": "Welcome & Registration",
    "prog.d1.e1.desc": "Main hall of the University of Yaoundé I",
    "prog.d1.e2.title": "Joint Opening Ceremony",
    "prog.d1.e2.desc": "Official opening of the CAITED Conference and EdTech Day Yaoundé 2026",
    "prog.d1.e3.title": "Plenary Session: \"Generative AI and Education\"",
    "prog.d1.e3.desc": "Keynote lecture by international experts in educational AI",
    "prog.d1.e4.title": "Parallel Research Sessions",
    "prog.d1.e4.desc": "Presentations of academic research on educational technologies",
    "prog.d1.e5.title": "Practical Workshops",
    "prog.d1.e5.desc": "Workshops on using digital tools in the classroom",
    "prog.d1.e6.title": "Welcome Cocktail",
    "prog.d1.e6.desc": "Networking and informal exchanges between participants",

    // Day 2
    "prog.d2.e1.title": "Keynote Conference: \"Innovative Pedagogies\"",
    "prog.d2.e1.desc": "New pedagogical approaches in the digital age",
    "prog.d2.e2.title": "Round Table: \"Digital Education Policies\"",
    "prog.d2.e2.desc": "Policy makers discuss strategies for digitalizing education",
    "prog.d2.e3.title": "Poster & Demonstration Session",
    "prog.d2.e3.desc": "Presentation of research projects and EdTech solution demonstrations",
    "prog.d2.e4.title": "EdTech Hackathon Pre-launch",
    "prog.d2.e4.desc": "Presentation of challenges and team formation for the hackathon",
    "prog.d2.e5.title": "Gala Dinner",
    "prog.d2.e5.desc": "Networking evening with partners and sponsors",

    // Day 3
    "prog.d3.e1.title": "EdTech Summit Welcome",
    "prog.d3.e1.desc": "Registration of participants at the EdTech Summit Yaoundé",
    "prog.d3.e2.title": "Official Opening of the EdTech Summit",
    "prog.d3.e2.desc": "Opening speeches by ministerial authorities",
    "prog.d3.e3.title": "Ministerial Panel: \"Vision 2030 for Digital Education\"",
    "prog.d3.e3.desc": "Ministers of Education, ICT and Higher Education",
    "prog.d3.e4.title": "EdTech Exhibition Showcase",
    "prog.d3.e4.desc": "Discovering innovative solutions from EdTech startups and companies",
    "prog.d3.e5.title": "EdTech Hackathon Final",
    "prog.d3.e5.desc": "Project presentations and winner announcements",
    "prog.d3.e6.title": "Closing Ceremony & Award Presentation",
    "prog.d3.e6.desc": "Summary of proceedings and announcement of concluded partnerships",

    // ── EXPOSITION ───────────────────────────────────────────
    "expo.title": "EdTech Exhibition Showcase",
    "expo.lead": "Discover innovative solutions from EdTech startups and companies",
    "expo.company1.title": "EduTech Solutions",
    "expo.company1.text": "Adaptive learning platform using AI to personalize educational pathways.",
    "expo.company1.badge": "Educational AI",
    "expo.company2.title": "LearnAI Cameroun",
    "expo.company2.text": "Pedagogical assistant based on generative AI for creating educational content.",
    "expo.company2.badge": "Generative AI",
    "expo.company3.title": "VirtualClass Africa",
    "expo.company3.text": "Virtual reality solutions for teaching science and technology subjects.",
    "expo.company3.badge": "Virtual Reality",
    "expo.company4.title": "EduGames Studio",
    "expo.company4.text": "Educational games for learning mathematics and languages.",
    "expo.company4.badge": "Serious Games",
    "expo.company5.title": "TeacherTools Pro",
    "expo.company5.text": "Suite of tools for classroom management and automated assessment.",
    "expo.company5.badge": "Teacher Tools",
    "expo.company6.title": "Campus Digital",
    "expo.company6.text": "Virtual campus platform for higher education institutions.",
    "expo.company6.badge": "Virtual Campus",
    "expo.demo.btn": "View Demo",
    "expo.stand.btn": "Book an Exhibition Stand",

    // ── HACKATHON ────────────────────────────────────────────
    "hack.title": "EdTech Hackathon 2026",
    "hack.lead": "48 hours to develop innovative solutions for Cameroonian education",
    "hack.challenges.title": "Hackathon Challenges",
    "hack.c1.title": "AI for Inclusive Education",
    "hack.c1.text": "Develop AI solutions that make education accessible to learners with disabilities.",
    "hack.c2.title": "Local Educational Content",
    "hack.c2.text": "Create tools to generate educational content adapted to the Cameroonian context.",
    "hack.c3.title": "Automated Assessment",
    "hack.c3.text": "Develop intelligent assessment systems to reduce teachers' workload.",
    "hack.c4.title": "Offline Learning",
    "hack.c4.text": "Create educational solutions that work without a stable internet connection.",
    "hack.info.title": "Practical Information",
    "hack.dates.label": "Dates",
    "hack.dates.text": "June 9-10, 2026 (starting June 9 at 5pm, ending June 10 at 6pm)",
    "hack.venue.label": "Venue",
    "hack.venue.text": "Digital Innovation Center, University of Yaoundé I",
    "hack.teams.label": "Teams",
    "hack.teams.text": "3-5 people per team, multidisciplinary recommended",
    "hack.prize.label": "Prize",
    "hack.prize.sub": "Total prizes to win + incubation in an EdTech accelerator",
    "hack.register.btn": "Register for the Hackathon",

    // ── EDITION 2025 ─────────────────────────────────────────
    "ed2025.badge": "PAST EDITION",
    "ed2025.title": "Looking Back at EdTech Day 2025",
    "ed2025.lead": "Relive the highlights of last year",
    "ed2025.carousel.title": "Featured News",
    "ed2025.carousel.subtitle": "Discover the department's flagship events",
    "ed2025.prev": "Previous",
    "ed2025.next": "Next",

    // News items 2025
    "news.creation.title": "EDTECH DAY | Creation",
    "news.creation.desc": "Create the educational content of tomorrow during the day dedicated to EdTech. Develop educational content with multimedia tools.",
    "news.creation.badge": "Creation",
    "news.debat-ia.title": "EDTECH DAY | Debate - Generative AI",
    "news.debat-ia.desc": "Teaching in the era of generative AI: what future for the teaching profession in Cameroon? With Prof. Fouda Ndjodo Marcel, Full Professor IGA MINESUP.",
    "news.debat-ia.badge": "Debate",
    "news.debat-integration.title": "EDTECH DAY | Debate - AI Integration",
    "news.debat-integration.desc": "Should we fear or encourage the integration and use of AI in Cameroonian schools? With Prof. Nicolas Gabriel Andjiga, Full Professor of Mathematics.",
    "news.debat-integration.badge": "Debate",
    "news.demo-eval.title": "EDTECH DAY | Demo - AI Assessment",
    "news.demo-eval.desc": "AI-assisted assessment in the teaching-learning process. Case of life and earth sciences in 3rd grade.",
    "news.demo-eval.badge": "Demo",
    "news.demo-lecon.title": "EDTECH DAY | Demo - AI Lesson",
    "news.demo-lecon.desc": "Setting up an AI-assisted lesson in the teaching-learning process. Case of a geography lesson.",
    "news.demo-lecon.badge": "Demo",
    "news.vainqueurs.title": "Hackathon 2025 Winners",
    "news.vainqueurs.desc": "Congratulations to the first prize winners of the hackathon organized by the ENS computer science department.",
    "news.vainqueurs.badge": "Winners",
    "news.details.btn": "View Details",

    // Actualités section
    "actu.title": "📰 News & Events",
    "actu.subtitle": "Discover the recent events and activities of the department",
    "actu.more.btn": "View more news",
    "actu.less.btn": "View less news",
    "actu.details.btn": "View Details",

    // Galerie
    "galerie.title": "EDTECH DAY 2025 Gallery",
    "galerie.subtitle": "Discover the highlights of our flagship event",

    // CTA
    "cta.title": "Stay connected with us",
    "cta.subtitle": "Follow our news and events so you don't miss anything",
    "cta.btn": "Contact Us",

    // ── SPEAKERS ─────────────────────────────────────────────
    "speakers.title": "Speakers & Panelists",
    "speakers.lead": "International and local experts in educational technologies and AI",
    "speakers.view.all": "View all speakers",
    "speaker1.role": "Educational AI Expert, UNESCO",
    "speaker1.bio": "Specialist in AI integration policies in African educational systems.",
    "speaker2.role": "Director of LITE, University of Yaoundé I",
    "speaker2.bio": "Researcher in educational technologies and director of the Laboratory of Computer Science and Educational Technologies.",
    "speaker3.role": "CEO, EduTech Global",
    "speaker3.bio": "EdTech entrepreneur with 15 years of experience in developing learning platforms.",
    "speaker4.role": "Generative AI Researcher, MIT",
    "speaker4.bio": "Pioneer in developing generative AI models for creating educational content.",

    // ── WORKSHOPS ────────────────────────────────────────────
    "workshops.title": "Demonstrations & Workshops",
    "workshops.lead": "Practical sessions to discover and master EdTech tools",
    "ws1.title": "Workshop: Creating with Generative AI",
    "ws1.text": "Learn to use ChatGPT, Midjourney and other AI tools to create educational content.",
    "ws1.level": "Level: Beginner",
    "ws2.title": "Demo: Teaching in Virtual Reality",
    "ws2.text": "Immersive VR class experience and demonstration of creating educational content in VR.",
    "ws2.level": "Level: Intermediate",
    "ws3.title": "Workshop: Moodle & LMS Platforms",
    "ws3.text": "Advanced configuration and use of Learning Management Systems for teaching.",
    "ws3.level": "Level: Advanced",

    // ── PARTNERS ─────────────────────────────────────────────
    "partners.title": "Partners & Sponsors",
    "partners.lead": "Organizations supporting EdTech Day Yaoundé 2026",
    "partners.organizers": "Organizing Partners",
    "partners.lite.desc": "Laboratory of Computer Science and Educational Technologies, University of Yaoundé I",
    "partners.scnef.desc": "Cameroonian Society of Digital Technology for Education and Training",
    "partners.sponsors": "Main Sponsors",
    "partners.become.btn": "Become a Partner",

    // ── REGISTRATION ─────────────────────────────────────────
    "register.title": "Registration",
    "register.lead": "Book your place for EdTech Day Yaoundé 2026",
    "register.formulas": "Registration Options",
    "ticket.student": "Student",
    "ticket.professional": "Professional",
    "ticket.company": "Company",
    "ticket.per.person": "per person",
    "ticket.per.company": "per company",
    "ticket.access3": "3-day access",
    "ticket.conferences": "Conferences",
    "ticket.workshops": "Workshops",
    "ticket.gala": "Gala Dinner",
    "ticket.networking": "VIP Networking",
    "ticket.stand": "Exhibition Stand",
    "ticket.logo": "Logo on website",
    "ticket.5access": "5 x 3-day access",
    "ticket.register.btn": "Register",
    "register.group": "For group registrations (+10 people), contact us at",

    // ── FOOTER ───────────────────────────────────────────────
    "footer.about": "Cameroon's flagship educational technology event, organized jointly with the CAITED Conference.",
    "footer.nav": "Navigation",
    "footer.links": "Useful Links",
    "footer.contact": "Contact",
    "footer.address": "University of Yaoundé I, Cameroon",
    "footer.hours": "Mon - Fri: 9am - 5pm",
    "footer.copyright": "© 2026 EdTech Day Yaoundé. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Use",

    // ── MODALS ───────────────────────────────────────────────
    "modal.expo.title": "Book an Exhibition Stand",
    "modal.expo.desc": "Book your stand to present your EdTech solutions at EdTech Day Yaoundé 2026.",
    "modal.expo.company": "Company Name",
    "modal.expo.contact": "Contact Person",
    "modal.expo.email": "Professional Email",
    "modal.expo.phone": "Phone",
    "modal.expo.stand": "Stand Type",
    "modal.expo.stand.small": "Small stand (3m²) - 150,000 FCFA",
    "modal.expo.stand.medium": "Medium stand (6m²) - 300,000 FCFA",
    "modal.expo.stand.large": "Large stand (12m²) - 500,000 FCFA",
    "modal.expo.message": "Description of your EdTech solutions",
    "modal.expo.submit": "Send Request",
    "modal.expo.alert": "Stand request sent successfully! We will contact you within 48 hours.",

    "modal.hack.title": "Register for EdTech Hackathon 2026",
    "modal.hack.team": "Team Name",
    "modal.hack.leader": "Team Leader",
    "modal.hack.leaderEmail": "Team Leader Email",
    "modal.hack.members": "Number of Members",
    "modal.hack.challenge": "Chosen Challenge",
    "modal.hack.ch1": "AI for inclusive education",
    "modal.hack.ch2": "Local educational content",
    "modal.hack.ch3": "Automated assessment",
    "modal.hack.ch4": "Offline learning",
    "modal.hack.submit": "Register",
    "modal.hack.alert": "Hackathon registration sent successfully!",

    "modal.sponsor.title": "Become a Partner",
    "modal.sponsor.org": "Organization Name",
    "modal.sponsor.contact": "Contact Name",
    "modal.sponsor.email": "Email",
    "modal.sponsor.type": "Partnership Type",
    "modal.sponsor.t.gold": "Gold (500,000 FCFA+)",
    "modal.sponsor.t.silver": "Silver (200,000 FCFA)",
    "modal.sponsor.t.bronze": "Bronze (100,000 FCFA)",
    "modal.sponsor.t.media": "Media Partner",
    "modal.sponsor.message": "Message (optional)",
    "modal.sponsor.submit": "Send Request",
    "modal.sponsor.alert": "Partnership request sent successfully!",

    "modal.contact.title": "Contact Us",
    "modal.contact.name": "Full Name",
    "modal.contact.email": "Email",
    "modal.contact.subject": "Subject",
    "modal.contact.message": "Message",
    "modal.contact.submit": "Send",
    "modal.contact.alert": "Message sent successfully!",

    "modal.close": "Close",
    "modal.cancel": "Cancel",

    // Ticket alert
    "ticket.alert.student": "Student (15,000 FCFA)",
    "ticket.alert.professional": "Professional (50,000 FCFA)",
    "ticket.alert.company": "Company (200,000 FCFA)",
    "ticket.alert.msg": "Registration for {type} package confirmed! You will be redirected to the payment page.",
};
