// ============================================================
//  FICHIER DE TRADUCTION - FRANÇAIS (fr.js)
//  EdTech Day Yaoundé 2026
//  Tous les textes du site en français sont stockés ici.
// ============================================================

const TRANSLATIONS_FR = {

    // ── META ──────────────────────────────────────────────────
    "page.title": "EdTech Day Yaoundé 2026 - Numériser les enseignements à l'ère de l'IA générative",
    "page.description": "EdTech Day Yaoundé 2026, événement phare des technologies éducatives au Cameroun, conjointement avec la Conférence CAITED, 27-28 Mai 2026, Université de Yaoundé.",

    // ── NAVIGATION ────────────────────────────────────────────
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.programme": "Programme",
    "nav.exposition": "Exposition",
    "nav.hackathon": "Hackathon",
    "nav.speakers": "Conférenciers",
    "nav.workshops": "Ateliers",
    "nav.partners": "Partenaires",
    "nav.register": "Inscription",
    "nav.register.btn": "S'inscrire",
    "nav.lang.btn": "FR/EN",

    // ── LANGUAGE SWITCHER ─────────────────────────────────────
    "lang.switcher.title": "Choisir la langue / Choose language",
    "lang.fr": "Français",
    "lang.en": "English",

    // ── TRANSLATION NOTICE ────────────────────────────────────
    "notice.title": "Traduction automatique",
    "notice.text": "Cette page est traduite automatiquement. Certains termes peuvent ne pas être exacts.",

    // ── HERO ──────────────────────────────────────────────────
    "hero.title": "EdTech Day Yaoundé 2026",
    "hero.subtitle": "Numériser les enseignements à l'ère de l'IA générative : quels leviers d'efficacité au Cameroun ?",
    "hero.description": "Événement phare des technologies éducatives au Cameroun, organisé conjointement avec la Conférence CAITED. Le 28 Mai 2026 est dédié au Sommet des EdTech à Yaoundé.",
    "hero.btn.register": "S'inscrire Maintenant",
    "hero.btn.programme": "Voir le Programme",

    // ── COUNTDOWN ────────────────────────────────────────────
    "countdown.title": "Compte à rebours",
    "countdown.days": "Jours",
    "countdown.hours": "Heures",
    "countdown.minutes": "Minutes",
    "countdown.seconds": "Secondes",
    "countdown.caited": "27 Mai : Conférence CAITED 2026",
    "countdown.caited.link": "Voir le site",
    "countdown.summit": "28 Mai : Sommet EdTech Yaoundé",
    "countdown.started": "L'événement a commencé !",

    // ── STATS ─────────────────────────────────────────────────
    "stats.days": "Jours d'événement",
    "stats.companies": "Entreprises EdTech",
    "stats.participants": "Participants attendus",
    "stats.speakers": "Conférenciers experts",

    // ── ABOUT ─────────────────────────────────────────────────
    "about.title": "À propos de l'événement",
    "about.lead": "L'EdTech Day Yaoundé 2026 est l'événement de référence dédié aux technologies éducatives au Cameroun et en Afrique centrale.",
    "about.p1": "Organisé conjointement avec la <strong>Conférence CAITED 2026 (Conférence sur les Avancées en Informatique et Technologies Éducatives pour le Développement)</strong>, cet événement de trois jours rassemble les acteurs clés du secteur éducatif, technologique et entrepreneurial.",
    "about.p2": "Le <strong>28 Mai 2026</strong> est spécialement dédié au <strong>Sommet des EdTech à Yaoundé</strong>, un événement stratégique qui réunit décideurs politiques, investisseurs, entrepreneurs et éducateurs pour dessiner l'avenir de l'éducation numérique au Cameroun.",
    "about.theme.label": "Thème 2026",
    "about.theme.text": "\"Numériser les enseignements à l'ère de l'IA générative : quels leviers d'efficacité au Cameroun ?\"",
    "about.theme.desc": "Explorer comment l'intelligence artificielle générative peut transformer l'enseignement et l'apprentissage dans le contexte camerounais.",
    "about.card.title": "Conjointement à la Conférence CAITED 2026",
    "about.card.text": "La 2ème édition de la EdTech Day de Yaoundé conjointe à la conférence internationale CAITED 2026, crée une synergie unique entre recherche académique et innovation entrepreneuriale orientées vers le développement durable.",
    "about.day1.label": "Conférence CAITED 2026",
    "about.day2.label": "Sommet EdTech",

    // ── OBJECTIVES ───────────────────────────────────────────
    "objectives.title": "Objectifs de l'EdTech Day 2026",
    "obj.innovation.title": "Innovation",
    "obj.innovation.text": "Présenter les innovations en IA générative appliquées à l'éducation et leur potentiel pour le Cameroun.",
    "obj.networking.title": "Réseautage",
    "obj.networking.text": "Créer des connections entre startups EdTech, investisseurs, éducateurs et décideurs politiques.",
    "obj.business.title": "Business",
    "obj.business.text": "Faciliter les opportunités d'affaires et les partenariats dans l'écosystème EdTech camerounais.",
    "obj.training.title": "Formation",
    "obj.training.text": "Former les enseignants et éducateurs aux outils numériques et à l'IA générative pour l'éducation.",

    // ── PROGRAMME ────────────────────────────────────────────
    "programme.title": "Programme des 3 jours",
    "programme.lead": "Un événement riche en conférences, ateliers, démonstrations et networking",
    "programme.day1.tab": "Jour 1",
    "programme.day1.sub": "8 Juin - Conférence CAITED",
    "programme.day2.tab": "Jour 2",
    "programme.day2.sub": "9 Juin - Conférence CAITED",
    "programme.day3.tab": "Jour 3",
    "programme.day3.sub": "10 Juin - Sommet EdTech",

    // Day 1
    "prog.d1.e1.title": "Accueil et enregistrement",
    "prog.d1.e1.desc": "Hall principal de l'Université de Yaoundé I",
    "prog.d1.e2.title": "Cérémonie d'ouverture conjointe",
    "prog.d1.e2.desc": "Ouverture officielle de la Conférence CAITED et de l'EdTech Day Yaoundé 2026",
    "prog.d1.e3.title": "Session plénière : \"IA générative et éducation\"",
    "prog.d1.e3.desc": "Conférence keynote par des experts internationaux en IA éducative",
    "prog.d1.e4.title": "Sessions parallèles de recherche",
    "prog.d1.e4.desc": "Présentations de recherches académiques sur les technologies éducatives",
    "prog.d1.e5.title": "Ateliers pratiques",
    "prog.d1.e5.desc": "Ateliers sur l'utilisation des outils numériques en classe",
    "prog.d1.e6.title": "Cocktail de bienvenue",
    "prog.d1.e6.desc": "Networking et échanges informels entre participants",

    // Day 2
    "prog.d2.e1.title": "Conférence keynote : \"Pédagogies innovantes\"",
    "prog.d2.e1.desc": "Nouvelles approches pédagogiques à l'ère du numérique",
    "prog.d2.e2.title": "Table ronde : \"Politiques éducatives numériques\"",
    "prog.d2.e2.desc": "Décideurs politiques discutent des stratégies de numérisation de l'éducation",
    "prog.d2.e3.title": "Session posters et démonstrations",
    "prog.d2.e3.desc": "Présentation de projets de recherche et démonstrations de solutions EdTech",
    "prog.d2.e4.title": "Pré-lancement Hackathon EdTech",
    "prog.d2.e4.desc": "Présentation des défis et formation des équipes pour le hackathon",
    "prog.d2.e5.title": "Dîner de gala",
    "prog.d2.e5.desc": "Soirée de networking avec les partenaires et sponsors",

    // Day 3
    "prog.d3.e1.title": "Accueil Sommet EdTech",
    "prog.d3.e1.desc": "Enregistrement des participants au Sommet EdTech Yaoundé",
    "prog.d3.e2.title": "Ouverture officielle du Sommet EdTech",
    "prog.d3.e2.desc": "Discours d'ouverture par les autorités ministérielles",
    "prog.d3.e3.title": "Panel ministériel : \"Vision 2030 pour l'éducation numérique\"",
    "prog.d3.e3.desc": "Ministres de l'Éducation, des TIC et de l'Enseignement Supérieur",
    "prog.d3.e4.title": "Vitrine d'exposition EdTech",
    "prog.d3.e4.desc": "Découverte des solutions innovantes des startups et entreprises EdTech",
    "prog.d3.e5.title": "Finale du Hackathon EdTech",
    "prog.d3.e5.desc": "Présentation des projets et annonce des gagnants",
    "prog.d3.e6.title": "Cérémonie de clôture et remise des prix",
    "prog.d3.e6.desc": "Synthèse des travaux et annonce des partenariats conclus",

    // ── EXPOSITION ───────────────────────────────────────────
    "expo.title": "Vitrine d'Exposition EdTech",
    "expo.lead": "Découvrez les solutions innovantes des startups et entreprises EdTech",
    "expo.company1.title": "EduTech Solutions",
    "expo.company1.text": "Plateforme d'apprentissage adaptatif utilisant l'IA pour personnaliser les parcours éducatifs.",
    "expo.company1.badge": "IA Éducative",
    "expo.company2.title": "LearnAI Cameroun",
    "expo.company2.text": "Assistant pédagogique basé sur l'IA générative pour la création de contenus éducatifs.",
    "expo.company2.badge": "IA Générative",
    "expo.company3.title": "VirtualClass Africa",
    "expo.company3.text": "Solutions de réalité virtuelle pour l'enseignement des sciences et techniques.",
    "expo.company3.badge": "Réalité Virtuelle",
    "expo.company4.title": "EduGames Studio",
    "expo.company4.text": "Jeux éducatifs pour l'apprentissage des mathématiques et des langues.",
    "expo.company4.badge": "Jeux Sérieux",
    "expo.company5.title": "TeacherTools Pro",
    "expo.company5.text": "Suite d'outils pour la gestion de classe et l'évaluation automatisée.",
    "expo.company5.badge": "Outils Enseignants",
    "expo.company6.title": "Campus Digital",
    "expo.company6.text": "Plateforme de campus virtuel pour les établissements d'enseignement supérieur.",
    "expo.company6.badge": "Campus Virtuel",
    "expo.demo.btn": "Voir la démo",
    "expo.stand.btn": "Réserver un stand d'exposition",

    // ── HACKATHON ────────────────────────────────────────────
    "hack.title": "Hackathon EdTech 2026",
    "hack.lead": "48 heures pour développer des solutions innovantes pour l'éducation camerounaise",
    "hack.challenges.title": "Défis du Hackathon",
    "hack.c1.title": "IA pour l'éducation inclusive",
    "hack.c1.text": "Développer des solutions d'IA qui rendent l'éducation accessible aux apprenants en situation de handicap.",
    "hack.c2.title": "Contenus éducatifs locaux",
    "hack.c2.text": "Créer des outils pour générer des contenus éducatifs adaptés au contexte camerounais.",
    "hack.c3.title": "Évaluation automatisée",
    "hack.c3.text": "Développer des systèmes d'évaluation intelligents pour réduire la charge de travail des enseignants.",
    "hack.c4.title": "Apprentissage hors ligne",
    "hack.c4.text": "Créer des solutions éducatives fonctionnant sans connexion internet stable.",
    "hack.info.title": "Informations pratiques",
    "hack.dates.label": "Dates",
    "hack.dates.text": "9-10 Juin 2026 (début le 9 Juin à 17h, fin le 10 Juin à 18h)",
    "hack.venue.label": "Lieu",
    "hack.venue.text": "Centre d'Innovation Numérique, Université de Yaoundé I",
    "hack.teams.label": "Équipes",
    "hack.teams.text": "3-5 personnes par équipe, multidisciplinaires recommandées",
    "hack.prize.label": "Prix",
    "hack.prize.sub": "Total des prix à gagner + incubation dans un accélérateur EdTech",
    "hack.register.btn": "S'inscrire au Hackathon",

    // ── EDITION 2025 ─────────────────────────────────────────
    "ed2025.badge": "ÉDITION PASSÉE",
    "ed2025.title": "Retour sur l'EdTech Day 2025",
    "ed2025.lead": "Revivez les moments forts de l'année dernière",
    "ed2025.carousel.title": "Actualités en Vedette",
    "ed2025.carousel.subtitle": "Découvrez les événements phares du département",
    "ed2025.prev": "Précédent",
    "ed2025.next": "Suivant",

    // News items 2025
    "news.creation.title": "EDTECH DAY | Création",
    "news.creation.desc": "Créez les contenus éducatifs de demain lors de la journée dédiée aux EdTech. Mettez sur pieds des contenus éducatifs avec des outils multimédias.",
    "news.creation.badge": "Création",
    "news.debat-ia.title": "EDTECH DAY | Débat - IA Générative",
    "news.debat-ia.desc": "Enseigner à l'ère de l'IA générative : quel avenir pour le métier d'enseignant au Cameroun ? Avec Prof. Fouda Ndjodo Marcel, Professeur Titulaire IGA MINESUP.",
    "news.debat-ia.badge": "Débat",
    "news.debat-integration.title": "EDTECH DAY | Débat - Intégration IA",
    "news.debat-integration.desc": "Faut-il craindre ou encourager l'intégration et les usages de l'IA à l'école camerounaise ? Avec Prof. Nicolas Gabriel Andjiga, Professeur Titulaire de Mathématiques.",
    "news.debat-integration.badge": "Débat",
    "news.demo-eval.title": "EDTECH DAY | Démo - Évaluation IA",
    "news.demo-eval.desc": "Évaluation assistée par Intelligence Artificielle dans le processus enseignement-apprentissage. Cas des sciences de la vie et de la terre en classe de 3ème.",
    "news.demo-eval.badge": "Démo",
    "news.demo-lecon.title": "EDTECH DAY | Démo - Leçon IA",
    "news.demo-lecon.desc": "Mise sur pieds d'une leçon assistée par Intelligence Artificielle dans le processus enseignement-apprentissage. Cas d'une leçon de géographie.",
    "news.demo-lecon.badge": "Démo",
    "news.vainqueurs.title": "Vainqueurs du Hackathon 2025",
    "news.vainqueurs.desc": "Félicitations aux lauréats du premier prix du hackathon organisé par le département informatique de l'ENS.",
    "news.vainqueurs.badge": "Lauréats",
    "news.details.btn": "Voir les détails",

    // Actualités section
    "actu.title": "📰 Actualités & Événements",
    "actu.subtitle": "Découvrez les événements et activités récents du département",
    "actu.more.btn": "Voir plus d'actualités",
    "actu.less.btn": "Voir moins d'actualités",
    "actu.details.btn": "Voir les détails",

    // Galerie
    "galerie.title": "Galerie EDTECH DAY 2025",
    "galerie.subtitle": "Découvrez les moments forts de notre événement phare",

    // CTA
    "cta.title": "Restez connectés avec nous",
    "cta.subtitle": "Suivez nos actualités et événements pour ne rien manquer",
    "cta.btn": "Nous contacter",

    // ── SPEAKERS ─────────────────────────────────────────────
    "speakers.title": "Conférenciers & Panélistes",
    "speakers.lead": "Experts internationaux et locaux en technologies éducatives et IA",
    "speakers.view.all": "Voir tous les conférenciers",
    "speaker1.role": "Expert en IA Éducative, UNESCO",
    "speaker1.bio": "Spécialiste des politiques d'intégration de l'IA dans les systèmes éducatifs africains.",
    "speaker2.role": "Directeur du LITE, Université de Yaoundé I",
    "speaker2.bio": "Chercheur en technologies éducatives et directeur du Laboratoire d'Informatique et des Technologies Éducatives.",
    "speaker3.role": "CEO, EduTech Global",
    "speaker3.bio": "Entrepreneure en EdTech avec 15 ans d'expérience dans le développement de plateformes d'apprentissage.",
    "speaker4.role": "Chercheur en IA Générative, MIT",
    "speaker4.bio": "Pionnier dans le développement de modèles d'IA générative pour la création de contenus éducatifs.",

    // ── WORKSHOPS ────────────────────────────────────────────
    "workshops.title": "Démonstrations & Ateliers",
    "workshops.lead": "Sessions pratiques pour découvrir et maîtriser les outils EdTech",
    "ws1.title": "Atelier : Créer avec l'IA Générative",
    "ws1.text": "Apprenez à utiliser ChatGPT, Midjourney et autres outils d'IA pour créer des contenus éducatifs.",
    "ws1.level": "Niveau : Débutant",
    "ws2.title": "Démo : Enseigner en Réalité Virtuelle",
    "ws2.text": "Expérience immersive de cours en RV et démonstration de création de contenus éducatifs en RV.",
    "ws2.level": "Niveau : Intermédiaire",
    "ws3.title": "Atelier : Moodle & Plateformes LMS",
    "ws3.text": "Configuration et utilisation avancée des Learning Management Systems pour l'enseignement.",
    "ws3.level": "Niveau : Avancé",

    // ── PARTNERS ─────────────────────────────────────────────
    "partners.title": "Partenaires & Sponsors",
    "partners.lead": "Organisations qui soutiennent l'EdTech Day Yaoundé 2026",
    "partners.organizers": "Partenaires Organisateurs",
    "partners.lite.desc": "Laboratoire d'Informatique et des Technologies Éducatives, Université de Yaoundé I",
    "partners.scnef.desc": "Société Camerounaise du Numérique pour l'Éducation et la Formation",
    "partners.sponsors": "Sponsors Principaux",
    "partners.become.btn": "Devenir Partenaire",

    // ── REGISTRATION ─────────────────────────────────────────
    "register.title": "Inscription",
    "register.lead": "Réservez votre place pour l'EdTech Day Yaoundé 2026",
    "register.formulas": "Formules d'inscription",
    "ticket.student": "Étudiant",
    "ticket.professional": "Professionnel",
    "ticket.company": "Entreprise",
    "ticket.per.person": "par personne",
    "ticket.per.company": "par entreprise",
    "ticket.access3": "Accès 3 jours",
    "ticket.conferences": "Conférences",
    "ticket.workshops": "Ateliers",
    "ticket.gala": "Dîner de gala",
    "ticket.networking": "Réseautage VIP",
    "ticket.stand": "Stand exposition",
    "ticket.logo": "Logo sur site web",
    "ticket.5access": "5 accès 3 jours",
    "ticket.register.btn": "S'inscrire",
    "register.group": "Pour les inscriptions de groupe (+10 personnes), contactez-nous à",

    // ── FOOTER ───────────────────────────────────────────────
    "footer.about": "Événement phare des technologies éducatives au Cameroun, organisé conjointement avec la Conférence CAITED.",
    "footer.nav": "Navigation",
    "footer.links": "Liens utiles",
    "footer.contact": "Contact",
    "footer.address": "Université de Yaoundé I, Cameroun",
    "footer.hours": "Lun - Ven: 9h - 17h",
    "footer.copyright": "© 2026 EdTech Day Yaoundé. Tous droits réservés.",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",

    // ── MODALS ───────────────────────────────────────────────
    "modal.expo.title": "Réserver un stand d'exposition",
    "modal.expo.desc": "Réservez votre stand pour présenter vos solutions EdTech lors de l'EdTech Day Yaoundé 2026.",
    "modal.expo.company": "Nom de l'entreprise",
    "modal.expo.contact": "Personne de contact",
    "modal.expo.email": "Email professionnel",
    "modal.expo.phone": "Téléphone",
    "modal.expo.stand": "Type de stand",
    "modal.expo.stand.small": "Petit stand (3m²) - 150 000 FCFA",
    "modal.expo.stand.medium": "Stand moyen (6m²) - 300 000 FCFA",
    "modal.expo.stand.large": "Grand stand (12m²) - 500 000 FCFA",
    "modal.expo.message": "Description de vos solutions EdTech",
    "modal.expo.submit": "Envoyer la demande",
    "modal.expo.alert": "Demande de stand envoyée avec succès ! Nous vous contacterons dans les 48h.",

    "modal.hack.title": "S'inscrire au Hackathon EdTech 2026",
    "modal.hack.team": "Nom de l'équipe",
    "modal.hack.leader": "Chef d'équipe",
    "modal.hack.leaderEmail": "Email du chef d'équipe",
    "modal.hack.members": "Nombre de membres",
    "modal.hack.challenge": "Défi choisi",
    "modal.hack.ch1": "IA pour l'éducation inclusive",
    "modal.hack.ch2": "Contenus éducatifs locaux",
    "modal.hack.ch3": "Évaluation automatisée",
    "modal.hack.ch4": "Apprentissage hors ligne",
    "modal.hack.submit": "S'inscrire",
    "modal.hack.alert": "Inscription au Hackathon envoyée avec succès !",

    "modal.sponsor.title": "Devenir Partenaire",
    "modal.sponsor.org": "Nom de l'organisation",
    "modal.sponsor.contact": "Nom du contact",
    "modal.sponsor.email": "Email",
    "modal.sponsor.type": "Type de partenariat",
    "modal.sponsor.t.gold": "Or (500 000 FCFA+)",
    "modal.sponsor.t.silver": "Argent (200 000 FCFA)",
    "modal.sponsor.t.bronze": "Bronze (100 000 FCFA)",
    "modal.sponsor.t.media": "Partenaire Média",
    "modal.sponsor.message": "Message (optionnel)",
    "modal.sponsor.submit": "Envoyer la demande",
    "modal.sponsor.alert": "Demande de partenariat envoyée avec succès !",

    "modal.contact.title": "Nous Contacter",
    "modal.contact.name": "Nom complet",
    "modal.contact.email": "Email",
    "modal.contact.subject": "Sujet",
    "modal.contact.message": "Message",
    "modal.contact.submit": "Envoyer",
    "modal.contact.alert": "Message envoyé avec succès !",

    "modal.close": "Fermer",
    "modal.cancel": "Annuler",

    // Ticket alert
    "ticket.alert.student": "Étudiant (15 000 FCFA)",
    "ticket.alert.professional": "Professionnel (50 000 FCFA)",
    "ticket.alert.company": "Entreprise (200 000 FCFA)",
    "ticket.alert.msg": "Inscription au forfait {type} enregistrée ! Vous allez être redirigé vers la page de paiement.",

    // ── NEW ENTRIES / PLACEHOLDERS ───────────────────────────
    "speakers.keynote.title": "Conférenciers Principaux (Keynote Speakers)",
    "speakers.keynote.lead": "Experts internationaux en informatique et technologies éducatives",
    "speaker.country.cm": "Cameroun",
    "speaker.specialty.it": "Expert en informatique et technologies éducatives",
    "speaker.btn.details": "Voir les détails - Conférencier Principal",

    "placeholder.image": "Image à venir",
    "placeholder.info": "Informations à venir...",
    "placeholder.domain": "Domaine : À venir",
    "placeholder.level": "Niveau : À venir",
    "placeholder.hours": "-- heures",

    "expo.ph1": "Exposant 1",
    "expo.ph2": "Exposant 2",
    "expo.ph3": "Exposant 3",
    "expo.ph4": "Exposant 4",
    "expo.ph5": "Exposant 5",
    "expo.ph6": "Exposant 6",

    "ws.ph1": "Atelier/Démo 1",
    "ws.ph2": "Atelier/Démo 2",
    "ws.ph3": "Atelier/Démo 3",

    "partners.institutional": "Partenaires Institutionnels",
    "partners.tech": "Partenaires Industrie Tech",
    "partners.publication": "Partenaires de Publication",
    "partners.media": "Partenaires Médias"
};
